Orders_service/Models/Order.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Orders_service.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Номер заказа")]
        public string Number { get; set; }
        [DataType(DataType.Date)]
        [Column(TypeName = "datetime2(7)")]
        [DisplayName("Дата")]
        public DateTime Date { get; set; }
        [DisplayName("Поставщик")]
        public int ProviderId { get; set; }
        public Provider? Provider { get; set; }
        public IList<OrderItem>? Items { get; set; }
    }
}

Orders_service/Pages/OrderItems/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Orders_service.Data;
using Orders_service.Models;

namespace Orders_service.Pages.OrderItems
{
    public class CreateModel : PageModel
    {
        private readonly Orders_service.Data.Orders_serviceContext _context;

        public CreateModel(Orders_service.Data.Orders_serviceContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["OrderId"] = new SelectList(_context.Order, "Id", "Number");
            return Page();
        }

        [BindProperty]
        public OrderItem OrderItem { get; set; }
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.OrderItem.Add(OrderItem);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Orders_service/Pages/OrderItems/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Orders_service.Data;
using Orders_service.Models;

namespace Orders_service.Pages.OrderItems
{
    public class DeleteModel : PageModel
    {
        private readonly Orders_service.Data.Orders_serviceContext _context;

        public DeleteModel(Orders_service.Data.Orders_serviceContext context)
        {
            _context = context;
        }

        [BindProperty]
      public OrderItem OrderItem { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderitem = await _context.OrderItem.FirstOrDefaultAsync(m => m.Id == id);

            if (orderitem == null)
            {
                return NotFound();
            }
            else 
            {
                OrderItem = orderitem;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }
            var orderitem = await _context.OrderItem.FindAsync(id);

            if (orderitem != null)
            {
                OrderItem = orderitem;
                _context.OrderItem.Remove(OrderItem);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Orders_service/Pages/OrderItems/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Orders_service.Data;
using Orders_service.Models;

namespace Orders_service.Pages.OrderItems
{
    public class DetailsModel : PageModel
    {
        private readonly Orders_service.Data.Orders_serviceContext _context;

        public DetailsModel(Orders_service.Data.Orders_serviceContext context)
        {
            _context = context;
        }

      public OrderItem OrderItem { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderitem = await _context.OrderItem.FirstOrDefaultAsync(m => m.Id == id);
            if (orderitem == null)
            {
                return NotFound();
            }
            else 
            {
                OrderItem = orderitem;
            }
            return Page();
        }
    }
}

Orders_service/Pages/OrderItems/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Orders_service.Data;
using Orders_service.Models;

namespace Orders_service.Pages.OrderItems
{
    public class EditModel : PageModel
    {
        private readonly Orders_service.Data.Orders_serviceContext _context;

        public EditModel(Orders_service.Data.Orders_serviceContext context)
        {
            _context = context;
        }

        [BindProperty]
        public OrderItem OrderItem { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderitem =  await _context.OrderItem.FirstOrDefaultAsync(m => m.Id == id);
            if (orderitem == null)
            {
                return NotFound();
            }
            OrderItem = orderitem;
           ViewData["OrderId"] = new SelectList(_context.Order, "Id", "Number");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(OrderItem).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrderItemExists(OrderItem.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool OrderItemExists(int id)
        {
          return _context.OrderItem.Any(e => e.Id == id);
        }
    }
}

Orders_service/Pages/Orders/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Orders_service.Data;
using Orders_service.Models;
using Orders_service.Utils;

namespace Orders_service.Pages.Orders
{
    public class CreateModel : PageModel
    {
        private readonly Orders_service.Data.Orders_serviceContext _context;

        [BindProperty]
        public Order Order { get; set; } = default!;

        [BindProperty]
        public string? ErrorMessage { get; set; }

        public CreateModel(Orders_service.Data.Orders_serviceContext context)
        {
            _context = context;
        }

        public override PageResult Page()
        {
            this.SetProviders(_context);
            return base.Page();
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostCreate()
        {
            if (!ModelState.IsValid || !AreItemsValid())
            {
                return Page();
            }

            _context.Order.Add(Order);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateException)
            {
                ErrorMessage = "Невозможно создать такой заказ";
                return Page();
            }

            ErrorMessage = null;
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostAddItem()
        {
            if (Order.Items == null)
                Order.Items = new List<OrderItem>();
            Order.Items.Add(new OrderItem() { Quantity = 0 });
            return Page();
        }

        public IActionResult OnPostRemoveItem(int itemIndex)
        {
            if (Order.Items == null)
                return Page();
            Order.Items.RemoveAt(itemIndex);
            return Page();
        }

        private bool AreItemsValid()
        {
            if (Order.Items == null)
                return true;
            foreach (var item in Order.Items)
            {
                if (item.Name == Order.Number)
                {
                    ErrorMessage = "Название элемента не может совпадать с номером заказа";
                    return false;
                }
            }
            return true;
        }
    }
}

Orders_service/Pages/Orders/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Orders_service.Data;
using Orders_service.Models;

namespace Orders_service.Pages.Orders
{
    public class DeleteModel : PageModel
    {
        private readonly Orders_service.Data.Orders_serviceContext _context;

        public DeleteModel(Orders_service.Data.Orders_serviceContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Order Order { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.Include(o => o.Provider).FirstOrDefaultAsync(m => m.Id == id);

            if (order == null)
            {
                return NotFound();
            }
            else 
            {
                Order = order;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }
            var order = await _context.Order.FindAsync(id);

            if (order != null)
            {
                Order = order;
                _context.Order.Remove(Order);
                var itemIds = Order.Items?.Where(i => i.Id != 0)?.Select(i => i.Id).ToList() ?? new List<int>();
                var itemsToRemove = await _context.OrderItem.Where(i => i.OrderId == Order.Id && !itemIds.Contains(i.Id)).ToArrayAsync();
                foreach (var item in itemsToRemove)
                    _context.OrderItem.Remove(item);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Orders_service/Pages/Orders/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Orders_service.Data;
using Orders_service.Models;

namespace Orders_service.Pages.Orders
{
    public class DetailsModel : PageModel
    {
        private readonly Orders_service.Data.Orders_serviceContext _context;

        public DetailsModel(Orders_service.Data.Orders_serviceContext context)
        {
            _context = context;
        }

      public Order Order { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.Include(o => o.Provider).Include(o => o.Items).FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            Order = order;
            return Page();
        }
    }
}

Orders_service/Pages/Orders/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Orders_service.Data;
using Orders_service.Models;
using Orders_service.Utils;

namespace Orders_service.Pages.Orders
{
    public class EditModel : PageModel
    {
        private readonly Orders_service.Data.Orders_serviceContext _context;

        [BindProperty]
        public Order Order { get; set; } = default!;

        [BindProperty]
        public string? ErrorMessage { get; set; }

        public EditModel(Orders_service.Data.Orders_serviceContext context)
        {
            _context = context;
        }

        public override PageResult Page()
        {
            this.SetProviders(_context);
            return base.Page();
        }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order =  await _context.Order.Include(o => o.Items).FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            Order = order;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostSave()
        {
            if (!ModelState.IsValid || !AreItemsValid())
            {
                return Page();
            }

            _context.Attach(Order).State = EntityState.Modified;
            var itemIds = Order.Items?.Where(i => i.Id != 0)?.Select(i => i.Id).ToList() ?? new List<int>();
            var itemsToRemove = await _context.OrderItem.Where(i => i.OrderId == Order.Id && !itemIds.Contains(i.Id)).ToArrayAsync();
            foreach (var item in itemsToRemove)
                _context.OrderItem.Remove(item);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrderExists(Order.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            catch (DbUpdateException)
            {
                ErrorMessage = "Невозможно сохранить текущие изменения";
                return Page();
            }

            ErrorMessage = null;
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostAddItem()
        {
            if (Order.Items == null)
                Order.Items = new List<OrderItem>();
            Order.Items.Add(new OrderItem() { Quantity = 0 });
            return Page();
        }

        public IActionResult OnPostRemoveItem(int itemIndex)
        {
            if (Order.Items == null)
                return Page();
            var item = Order.Items[itemIndex];
            Order.Items.Remove(item);
            return Page();
        }

        private bool OrderExists(int id)
        {
          return _context.Order.Any(e => e.Id == id);
        }

        private bool AreItemsValid()
        {
            if (Order.Items == null)
                return true;
            foreach (var item in Order.Items)
            {
                if (item.Name == Order.Number)
                {
                    ErrorMessage = "Название элемента не может совпадать с номером заказа";
                    return false;
                }
            }
            return true;
        }
    }
}

Orders_service/Pages/Providers/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Orders_service.Data;
using Orders_service.Models;

namespace Orders_service.Pages.Providers
{
    public class CreateModel : PageModel
    {
        private readonly Orders_service.Data.Orders_serviceContext _context;

        public CreateModel(Orders_service.Data.Orders_serviceContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Provider Provider { get; set; }
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Provider.Add(Provider);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Orders_service/Pages/Orders/Create.cshtml
@page
@model Orders_service.Pages.Orders.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" id="createForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Order.Number" class="control-label"></label>
                <input asp-for="Order.Number" class="form-control" />
                <span asp-validation-for="Order.Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Order.Date" class="control-label"></label>
                <input asp-for="Order.Date" class="form-control" />
                <span asp-validation-for="Order.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Order.ProviderId" class="control-label"></label>
                <select asp-for="Order.ProviderId" class ="form-control" asp-items="ViewBag.Providers"></select>
            </div>
            <p></p>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Order.Items[0].Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Order.Items[0].Quantity)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Order.Items[0].Unit)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Order?.Items?.Count; i++)
                    {
                        <tr>
                            <td>
                                <input asp-for="Order.Items[i].Name" class="form-control" />
                            </td>
                            <td>
                                <input asp-for="Order.Items[i].Quantity" class="form-control" />
                            </td>
                            <td>
                                <input asp-for="Order.Items[i].Unit" class="form-control" />
                            </td>
                            <td>
                                <input type="hidden" name="itemIndex" value="@i" />
                                <input asp-page-handler="RemoveItem" formnovalidate type="submit" value="Remove" />
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <input asp-page-handler="AddItem" type="submit" value="Add item" />
            <p></p>
            <div class="form-group">
                <p style="color:red">
                    @Html.Raw(Model.ErrorMessage)
                </p>
                <input asp-page-handler="Create" type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <p></p>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Orders_service/Pages/Orders/Delete.cshtml
@page
@model Orders_service.Pages.Orders.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Number)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Provider)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Provider.Name)
        </dd>
    </dl>
    
    <form method="post">
        <p></p>
        <input type="hidden" asp-for="Order.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>

    <div>
        <p></p>
        <a asp-page="./Details" asp-route-id="@Model.Order?.Id">Back to Details</a> |
        <a asp-page="./Index">Back to List</a>
    </div>
</div>

Orders_service/Pages/Orders/Details.cshtml
@page
@model Orders_service.Pages.Orders.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Number)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Provider)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.Provider.Name)
        </dd>
    </dl>
    <div class="col-md-4">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Order.Items[0].Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Order.Items[0].Quantity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Order.Items[0].Unit)
                    </th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Order?.Items?.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(model => model.Order.Items[i].Name)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Order.Items[i].Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Order.Items[i].Unit)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Order?.Id">Edit</a> |
    <a asp-page="./Delete" asp-route-id="@Model.Order?.Id">Delete</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Orders_service/Pages/Orders/Edit.cshtml
@page
@model Orders_service.Pages.Orders.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Order.Id" />
            <div class="form-group">
                <label asp-for="Order.Number" class="control-label"></label>
                <input asp-for="Order.Number" class="form-control" />
                <span asp-validation-for="Order.Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Order.Date" class="control-label"></label>
                <input asp-for="Order.Date" class="form-control" />
                <span asp-validation-for="Order.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Order.ProviderId" class="control-label"></label>
                <select asp-for="Order.ProviderId" class="form-control" asp-items="ViewBag.Providers"></select>
                <span asp-validation-for="Order.ProviderId" class="text-danger"></span>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Order.Items[0].Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Order.Items[0].Quantity)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Order.Items[0].Unit)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    
                    @for (int i = 0; i < Model.Order?.Items?.Count; i++)
                    {
                        <tr>
                            <td>
                                <input asp-for="Order.Items[i].Name" class="form-control" />
                                <input type="hidden" asp-for="Order.Items[i].Id" />
                            </td>
                            <td>
                                <input asp-for="Order.Items[i].Quantity" class="form-control" />
                            </td>
                            <td>
                                <input asp-for="Order.Items[i].Unit" class="form-control" />
                            </td>
                            <td>
                                <input type="hidden" name="itemIndex" value="@i" />
                                <input asp-page-handler="RemoveItem" formnovalidate type="submit" value="Remove" />
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <input asp-page-handler="AddItem" type="submit" value="Add item" />
            <p></p>
            <div class="form-group">
                <p style="color:red">
                    @Html.Raw(Model.ErrorMessage)
                </p>
                <input asp-page-handler="Save" type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <p></p>
    <a asp-page="./Details" asp-route-id="@Model.Order?.Id">Back to Details</a> |
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Orders_service/Pages/Orders/Index.cshtml
@page "/"
@model Orders_service.Pages.Orders.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>

<form method="post">
    <p>
        From @Html.EditorFor(model => model.FromDateFilter) to @Html.EditorFor(model => model.ToDateFilter) <div class="col-md-4">Provider <select asp-for="ProviderId" class="form-control" asp-items="ViewBag.Providers"></select></div>
    </p>
    <p>
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Orders[0].Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Orders[0].Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Orders[0].ProviderId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Orders) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Provider.Name)
            </td>
            <td>
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>